### ISSUE TITLE
TypeError: metaclass conflit

### ISSUE THREAD

**Issue by Hectormxy** [perfectly-balanced/PathBench#71]
I have run the following commands on Ubuntu20.04 in Anaconda Environment with python 3.8.10 : 

 **python3 tests/test_graphics/test_labyrinth_A.py --spawn-display --view-display**

And I have encountered the following error:

Traceback (most recent call last):
  File "tests/test_graphics/test_labyrinth_A.py", line 6, in <module>
    from common import init, destroy, wait_for, take_screenshot
  File "/home/mao/GVD/DataSet/PathBench/tests/test_graphics/common.py", line 24, in <module>
    from simulator.services.resources.directory import Directory  # noqa: E402
  File "/home/mao/GVD/DataSet/PathBench/src/simulator/services/resources/directory.py", line 16, in <module>
    from simulator.services.resources.smart_unpickle import load as smart_load
  File "/home/mao/GVD/DataSet/PathBench/src/simulator/services/resources/smart_unpickle.py", line 11, in <module>
    class Point(NamedTuple, torch.Tensor):
**TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases**

I will really appreciate it  if anyone would offer me some help.

**Comment by royzhang12** [comment]
I have met the same problem and already solved it. The metaconflict might be caused by the version of the torch. The reason might be that they have added some metaclasses into the torch for the lastest version(I am not quite sure as it is just a comment I see from the web). Try to degrade the version of your torch, which might be helpful. I used torch=1.4.0, torchvision=0.5.0. In another way, you can just delete the torch.Tensor from the class point(....), which may also works.
